name: project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  awesome_snackbar_content: ^0.1.4
  cached_network_image: ^3.4.1
  card_loading: ^0.3.2
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.5.0
  curved_navigation_bar: ^1.0.6
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  firebase_storage: ^12.3.6
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.1
  flutter_slidable: ^3.1.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.7
  google_sign_in: ^6.2.2
  image_picker: ^0.8.7+5
  intl_phone_number_input: ^0.7.4
  loading_animation_widget: ^1.3.0
  lottie: ^3.1.3
  motion_tab_bar: ^2.0.4
  persistent_bottom_nav_bar: ^6.2.1
  sign_in_with_apple: ^6.1.4
  slide_to_act: ^2.0.2
  slider_button: ^2.1.0
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.2


    
flutter_icons:
  android: true
  ios: true
  image_path: "assets/Nysa_logo.jpg"
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Nysa2.png
    - assets/Nysa_logo.jpg
    - assets/men_categories.jpg
    - assets/babies_categories.jpg
    - assets/women_categories.jpg
    - assets/custom_categories.jpg
    - assets/hruta.png
    - assets/ritesh.jpg
    - assets/kids.png
    - assets/success.gif
    - assets/gpay.png
    - assets/no_favorites.png
    - assets/no_cart.jpg
    - assets/offer1.jpg
    - assets/offer2.jpg
    - assets/offer3.jpg
    - assets/favorites2.gif
    - assets/favorites.gif
    - assets/google.png
    
