name: routegen
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  image_picker: ^0.8.4+4
  flutter_launcher_icons: ^0.14.1
  google_nav_bar: ^5.0.7
  dropdown_search: ^6.0.1
  line_icons: ^2.0.3
  flutter_slidable: ^3.1.1
  cloud_firestore: ^5.4.5
  firebase_auth: ^5.3.2
  firebase_core: ^3.7.0
  firebase_database: ^11.1.5
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.3.3
  flutter_qr_bar_scanner: ^3.0.2
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/